### ISSUE TITLE
problem with new version mr-doc-theme-default 1.4.0

### ISSUE THREAD

**Issue by solitarywit** [mr-doc/mr-doc#107]
npm WARN deprecated grunt-mrdoc@0.1.4: All versions older than v0.1.9 have a bug that fail in found mrdoc dep
npm ERR! Linux 3.14.27-25.47.amzn1.x86_64
npm ERR! argv "/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJs-Current/bin/node" "/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJs-Current/bin/npm" "install" "--no-optional"
npm ERR! node v0.12.0
npm ERR! npm v2.5.1
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: mr-doc-theme-default@'>=1.4.0 <2.0.0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["1.0.0","1.0.3","1.3.0","1.3.1"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

**Comment by iwatakeshi** [comment]
@scottnath Thanks for the report! I'll check on it :)

**Comment by iwatakeshi** [comment]
@solitarywit Which version of grunt-mrdoc are you using? It seems to me that you might be using an older verison? Try updating grunt-mrdoc and let me know if the issue persists. :)

**Comment by solitarywit** [comment]
@iwatakeshi I tried, but not fixed, latest 0.1.9, it use mr-doc in deps
"dependencies": {
		"mr-doc": "*"
	},

**Comment by iwatakeshi** [comment]
@solitarywit Yeah seems weird because it works on my end for both Mac and PC. Would you have a sample repo that you can create to reproduce this problem? I can then fork it and test it out on my end.

**Comment by solitarywit** [comment]
@iwatakeshi fixed) thank you)
