### ISSUE TITLE
Feature request/support question - displaying available options for options object

### ISSUE THREAD

**Issue by ORESoftware** [mr-doc/mr-doc#114]
I am liking this a lot so far, way better than JSDoc.

One thing I don't know how to do, (not sure if it's available) is to display the options for an options object

For example this:

![screenshot 2016-04-03 13 49 20](https://cloud.githubusercontent.com/assets/11139560/14234879/1764f37a-f9a3-11e5-959f-69a55e406b68.png)

I could do it manually like so:

![screenshot 2016-04-03 13 52 54](https://cloud.githubusercontent.com/assets/11139560/14234895/66be0204-f9a3-11e5-99e5-b4a268fbdadb.png)

but doing it manually is of course problematic; let me know if this feature exists or not! If it doesn't it would great to have, thanks

**Comment by iwatakeshi** [comment]
:+1: Hey @ORESoftware  thanks for the bringing up the issue from #7 . I completely agree with you that this is a must have feature. Unfortunately, v3 doesn't support it but I am working on v4 which I will need lots of help.

One of the things I'm not sure yet is how [doctrine](https://github.com/eslint/doctrine) handles objects but I'll definitely look into it. I'm also thinking to make the parser somewhat pluggable so it can be extended but I haven't thought of how yet.

If you're interested, you can check out the fork of the next version [here](https://github.com/iwatakeshi/mr-doc) and let me know some ways I can get that feature to work. :smile:

**Comment by ORESoftware** [comment]
cool thanks!

**Comment by ORESoftware** [comment]
I am really liking this a lot, your lib can what I want and jsdoc cannot. really looking forward to feature that can show all available options of an options obj!!

**Comment by iwatakeshi** [comment]
See #115 for possible solution but closing this for now.
