### ISSUE TITLE
Unsupported URL Type: github:mr-doc/compiler#v1.0.0

### ISSUE THREAD

**Issue by vanyadymousky** [mr-doc/mr-doc#117]
Hi. Running mr-doc (through grunt-mrdoc package) got following issue: 

npm ERR! Linux 3.14.27-25.47.amzn1.x86_64
npm ERR! argv "/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJs-Current/bin/node" "/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJs-Current/bin/npm" "i" "--no-optional"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1

npm ERR! Unsupported URL Type: github:mr-doc/compiler#v1.0.0

Can someone help with that?

**Comment by iwatakeshi** [comment]
@vanyadymousky Thanks for the feedback. I guess npm doesn't like to download from github repos. I'll have to publish the compiler and the parser to npm and see if that will fix it.

**Comment by iwatakeshi** [comment]
@vanyadymousky So the package should be fixed now however, you may have to upgrade your node and npm version because the least required node version is 5.
