### ISSUE TITLE
Additional Enhancements for Doxx

### ISSUE THREAD

**Issue by iwatakeshi** [mr-doc/mr-doc#73]
There's a few more things I think Doxx can do that would most likely ease developers with customization with the template. 

I would like have your thoughts on adding an option for bower and using that for the templates. We can keep the old template but create a new template that uses bower if the user opts in for a new one. 

Also if you need a helping hand, I will be willing to be a collaborator. Of course, I have some projects of my own that I am working  on (which they really needed Doxx haha) but I can try looking into fixing other issues. Just let me know how you do things with versioning and I'll try to follow it. :)

**Comment by FGRibreau** [comment]
Hello @iwatakeshi,

> I would like have your thoughts on adding an option for bower and using that for the templates. 

Indeed, we could extend the "--template" to detect if its a bower dependency (e.g. if the string contains an @ it's a bower dependency) and install (or update it) asynchronously before running the next process steps. That way the documentation template could be required via bower, what do you think?

> Also if you need a helping hand, I will be willing to be a collaborator. 

Yeah, no problem! Let's do that!

> how you do things with versioning and I'll try to follow it. :)

I follow semver:

> Given a version number MAJOR.MINOR.PATCH, increment the:
> MAJOR version when you make incompatible API changes,
> MINOR version when you add functionality in a backwards-compatible manner, and
> PATCH version when you make backwards-compatible bug fixes.

**Comment by iwatakeshi** [comment]
Awesome, thanks @FGRibreau! :+1: 

> Indeed, we could extend the "--template" to detect if its a bower dependency (e.g. if the string contains an @ it's a bower dependency) and install (or update it) asynchronously before running the next process steps. That way the documentation template could be required via bower, what do you think?

That sounds like a possibility. A pseudo code for bash may be:

```bash
# parse a whole folder
  $ doxx --source lib --bower true --target docs
# or the shortcut:
  $ doxx -s lib -b true -T docs

# parse a whole folder and use a specific template with bower
  $ doxx --template ./view/myowntpl.jade --bower ./bower.json --source lib --target docs
# or the shortcut:
  $ doxx -t ./view/myowntpl.jade -b ./bower.json -s lib -T  docs
```

Although for the parsing a whole folder, I would love to use an implied command like the following:

```bash
# parse a whole folder
  $ doxx --source lib --bower --target docs
# or the shortcut:
  $ doxx -s lib -b -T docs
```
So instead of checking if `-b` is a `boolean` we can just check if it's an empty string. 

As far as installing bower, I'm think of creating a new class called `Bower` which takes an option as a param of the constructor and then using a local bower to install the dependencies at the provided target. And yes, async does sound like a good idea.

What do you think?

**Comment by FGRibreau** [comment]
` --bower true` seems redoundant `--bower` or `-b` would be enough right?

> As far as installing bower, I'm think of creating a new class called Bower which takes an option as a param of the constructor and then using a local bower to install the dependencies at the provided target. 
:+1: sounds good to me!

**Comment by iwatakeshi** [comment]
Yes, I think `-b` or `--bower` would be better. I'm in the middle of researching of researching a couple of things to enhance doxx and so far I thought to try a GitHub template and see how that would work out. A fork of the template can be found here: https://github.com/iwatakeshi/doxx-theme-cayman

Another thought I had about doxx was making it a language agnostic documentation generator. I'll push the idea on the develop branch in a bit but basically I'm just seeing how we can use Prism's tokenize method... your thoughts?

**Comment by iwatakeshi** [comment]
Here's the develop branch: https://github.com/iwatakeshi/doxx/tree/develop

You'll need to have babel installed globally and then run:

```bash
$ babel-node ./lib/3.0.0/test
```

It should output the comments only. Of course all this is just to give me an idea of what Prism.js can do.

**Comment by FGRibreau** [comment]
:+1: for https://github.com/iwatakeshi/doxx-theme-cayman

About the develop branch, I really really prefer whenjs over Q, would you mind make the switch? 
Otherwise than that, it's good for me :)

**Comment by iwatakeshi** [comment]
:+1:  No problem, I definitely can do that. Most seemed to use Q so I just gave it a shot. haha.

**Comment by iwatakeshi** [comment]
I must say that the doxx-theme-cayman came out real good. It's pretty much ready but there's a couple of things that needs be done before moving on with theming.

First, we'll need to create a component that will copy the theme and its dependencies or assets into the same dir as the docs. Here are some thoughts/questions that I had and would like to hear your thoughts as well:

We could:

**Comment by FGRibreau** [comment]
> "For this, if users would like to create custom templates, we'll need to create a guideline."

Just provide a starter-template :)

> "Create a themes repo and have users pull request their custom themes there."

I'm not very fond if this option, it's better if users can install any template they want

> Create a theme searching site similar to how gulp.js search their plugins.

I would not rate this as high priority feature, a lot still needs to be done on Doxx itself :)

**Comment by iwatakeshi** [comment]
> Just provide a starter-template :)

That sounds good then. I'll create a repo and name it doxx-theme-starter

>  I'm not very fond if this option, it's better if users can install any template they want using bower :) However, every template could start with "doxx-theme-"

I agree, any thoughts or a pseudo code to have Doxx install the templates?

> I would not rate this as high priority feature, a lot still needs to be done on Doxx itself :)

**Comment by iwatakeshi** [comment]
Mobile is hard....haha

> I would not rate this as high priority feature, a lot still needs to be done on Doxx itself :)

I agree, I would add this to a milestone and slowly work on it.

**Comment by FGRibreau** [comment]
:+1:

**Comment by iwatakeshi** [comment]
I'll close this for now. I'll be creating milestones if needed.
