### ISSUE TITLE
Setup themes through npm instead of bower

### ISSUE THREAD

**Issue by iwatakeshi** [mr-doc/mr-doc#79]
This is more of a follow up on adding themes to Doxx from #73 . 

Here's the progress:

* [x] Create [doxx-theme-cayman](https://www.github.com/iwatakeshi/doxx-theme-cayman)
* [x] Create starter kit, [doxx-theme-starter-kit](https://www.github.com/iwatakeshi/doxx-theme-stater-kit), for those who want to create custom templates.
* [x] Create [doxx-theme-default](https://www.github.com/iwatakeshi/doxx-theme-default)
* [x] Introduce a theme class that handles theme installation.
* [x] Clean up.

**Comment by cliftonc** [comment]
I know the current approach with themes is to use bower to install the theme in a separate folder when running dox, and then require it there by doxx.

Other projects, such as gulp, have a slightly more idiomatic approach that I think may be worth at least considering.

Lets say you want to use ```doxx``` and ```doxx-theme-cayman``` in your project to document it, and ideally have a simple wrapper either in the ```package.json``` or in a build script that re-generates the documentation for you.

 - You install the main project: ```npm install doxx --save-dev```.
-  You add an npm command:  ```"docs": "doxx --source src --target docs --theme cayman```
- You run ```npm run docs```:

```
Doxx [warning]:  Theme 'cayman' not found, try "npm install doxx-theme-cayman", using default.
Doxx [info]:  Generating docs using [default] theme
```

- You then run ```npm install doxx-theme-cayman --save-dev```

In this model Doxx would be looking for the themes as being installed a level up from itself, and the default theme would be a direct dependency of Doxx and so installed with it.

This would remove a lot of the Theme code, and basically make it's task simply finding the module or falling back to the default.

**Comment by cliftonc** [comment]
This has one other big advantage, in that when doing development on a theme, you can just ```npm link``` the theme into Doxx and test it on Doxx itself very simply.

**Comment by cliftonc** [comment]
Submitting a PR feels really pre-emptive given no discussion, so here is a gist showing how it might look:  https://gist.github.com/cliftonc/46661fdd9583f0111234

**Comment by iwatakeshi** [comment]
@cliftonc Thanks for the feedback and sorry I just woke up. Yeah, I'm not too sure... @FGRibreau any thoughts on this?

**Comment by iwatakeshi** [comment]
@cliftonc Should I leave open?

**Comment by FGRibreau** [comment]
@cliftonc +1 for using npm instead of bower. (cc @iwatakeshi ). 
Closing this issue for new but I will greatly appreciate a PR in that direction if that's also OK with @iwatakeshi  :)

**Comment by iwatakeshi** [comment]
@FGRibreau @cliftonc That's fine with me just as long the commands, the API in Theme and the functionality is the same. :)

**Comment by iwatakeshi** [comment]
@FGRibreau I'm going to reopen this issue until @cliftonc changes the backend from bower to npm -- @cliftonc if you decide to do so. I do want to bring an idea/update/milestone to the table which is having a site for theme searching. I don't think this will happen in anytime soon but just keep in mind about it when making any changes.

**Comment by FGRibreau** [comment]
@iwatakeshi Ok, so I changed the issue title then :)

**Comment by iwatakeshi** [comment]
:+1:

**Comment by cliftonc** [comment]
@iwatakeshi - no problem, I've done something similar in a previous project (re. the theme search - https://github.com/cliftonc/calipso - though a bit old now), and it is even easier now as there is a simple npm api that you can use.

It *will* remove the need for the cache commands - as the end user will be responsible for managing the version of the theme in the ```package.json```, if they want the new version of a theme they just bump the version as normal.   Makes it much more explicit.

Let me pull together a PR and we can use that to discuss how it looks / works compared to the current bower version - easier to discuss in the real than the abstract.

On a side note, we should create a roadmap section on the readme as it will help others contribute and get a good feel for the ambitions of the project.

**Comment by iwatakeshi** [comment]
@cliftonc That's fine with me then :). For the roadmap, I'm for it. @FGRibreau I'll edit the readme later and we'll publish the next patch as `2.1.1`. 

I'm thinking `2.2.0` will be the switch from bower to npm. Since I think it will remove some of the API. Then `2.2.1` will bring theme searching (I think this is just to update the readme and nothing in the API). Then hopefully in the future we can bring the capability to parse a generic language and create docs from it using plugins for Doxx or something... (*way in the future*).

@FGRibreau I'd recommend that we create an organization/repo for Doxx and move doxx, doxx-theme-starter-kit, and the theme searching site over there.

@FGRibreau @cliftonc any thoughts? :)

**Comment by FGRibreau** [comment]
>  @FGRibreau I'll edit the readme later and we'll publish the next patch as 2.1.1.

:ok:

> I'm thinking 2.2.0 will be the switch from bower to npm.

I think it's a breaking change, since `--theme` will know look for an npm package instead of a bower one. So we may want to release a 3.0.0 for that.

> Then hopefully in the future we can bring the capability to parse a generic language and create docs from it using plugins for Doxx or something... (way in the future).

There is already some documentor that works cross-languages, I don't think we need one more, however we deeply need a real JavaScript documentor that works well with javascript ES5/ES6. 

> @FGRibreau I'd recommend that we create an organization/repo for Doxx and move doxx, doxx-theme-starter-kit, and the theme searching site over there.

Indeed, I can do that, it may even be a good idea to change the name as ["Doxx" is way too related to other bad things](http://fr.urbandictionary.com/define.php?term=doxx), what do you think?

- https://github.com/javascript-documentation-generator would be great for SEO :)

**Comment by iwatakeshi** [comment]
> I think it's a breaking change, since `--theme` will know look for an npm package instead of a bower one. So we may want to release a 3.0.0 for that.

Sounds good :)

> There is already some documentor that works cross-languages, I don't think we need one more, however we deeply need a real JavaScript documentor that works well with javascript ES5/ES6.

Hmm how about creating something similar to Prism. We'll create a plugin called 'our new name-lang-javascript` and have users create their own. 

>@iwatakeshi Indeed, I can do that, it may even be a good idea to change the name as "Doxx" is way too related to other bad things, what do you think?

Mmmm may Dokx? I'll think of something. :)

**Comment by iwatakeshi** [comment]
@cliftonc Just to make sure I'm understanding what's going on from #87. This part isn't finished yet correct?

**Comment by cliftonc** [comment]
This is finished, but you need to publish the Cayman theme to npm.  The docs generation PR needs a new home page.

**Comment by iwatakeshi** [comment]
:+1: :ok: thanks because I was a bit confused on what was going on. :) The follow up on cayman theme can be found at https://github.com/mr-doc/mr-doc-theme-cayman/issues/7 :) I also committed the next update so any help on testing it would be greatly appreciated ;)

**Comment by cliftonc** [comment]
Will try to take a look tomorrow, been a bit flat out at work this week so little time to help out, but all the changes look good. 

Thanks for publishing the cayman theme to npm.

**Comment by iwatakeshi** [comment]
:+1: Oh no, thank you!
