### ISSUE TITLE
New name for Doxx

### ISSUE THREAD

**Issue by iwatakeshi** [mr-doc/mr-doc#83]
Bringing the discussion from #79 to here, Doxx is needing a new name. @FGRibreau @cliftonc any thoughts on this. I haven't come up with one yet but looking at the thesaurus for "documentation" doesn't help too much. We could use names of people to think outside-the-box. e.g. *`name`, your personal source documenter.*

**Comment by iwatakeshi** [comment]
@FGRibreau A few names we could use and is available on Github org:
* `name: mr-doc alias: doc`
* `name: mr-dox alias: [mrd, dox]`
* `name: doc-doc alias: [doc, dd]`
* `name: doxcer alias: [doxcer, dox, doc]`
* `name: lucy-doc alias: lucy`

Also, let me know if you would like for me to create the org. I'll be willing to manage it if you don't have the time.

**Comment by FGRibreau** [comment]
@iwatakeshi I like **mr-doc** ! Don't worry, I'll create the org :) (it's done by the way)

**Comment by iwatakeshi** [comment]
@FGRibreau :+1: Awesome! I've already started some transfers. You'll have to rename the repo once it has been completed

**Comment by FGRibreau** [comment]
@iwatakeshi 

- perfect, tell me when you want me to move doxx/ repository as well
- I got no idea :)

**Comment by FGRibreau** [comment]
@iwatakeshi I moved the project, I updated what I could, I will live you the rest :)

**Comment by iwatakeshi** [comment]
:+1: :ok: :)
