### ISSUE TITLE
A new image for Mr. Doc

### ISSUE THREAD

**Issue by iwatakeshi** [mr-doc/mr-doc#88]
@FGRibreau Good news, I've just talked with my cousin who draws [awesome art](http://www.matsuyacreative.com/benmatsuya/art/) and he agreed to draw for Mr. Doc. I thought the image should be simple so I asked him if he could draw us a silhouette that has a gentlemen with a typewriter. He will creating an image for the profile pic and the readme file in which the readme file, there will be a tagline that says, "Your personal source documenter". Would that be ok with you?

**Comment by FGRibreau** [comment]
@iwatakeshi that's fine with me :)

**Comment by iwatakeshi** [comment]
@FGRibreau Image is ready! You can try adding to Mr. Doc's Organization Pic.
Source: http://f.cl.ly/items/0X1l2b0k053m2e1b1j09/Mr.%20Doc.jpg

**Comment by FGRibreau** [comment]
@iwatakeshi done :) (it may take some time to update)
