### ISSUE TITLE
Theme output in docs folder

### ISSUE THREAD

**Issue by cliftonc** [mr-doc/mr-doc#93]
If we use the ```gulp docs``` command and use that to push to the ```gh-pages``` branch we should .gitignore the ```docs/themes``` folder:

https://github.com/mr-doc/mr-doc/tree/master/docs/themes/doxx-theme-default

Why?

- It means we dont get tonnes of HTML diffs in commits to code that just blur stuff (e.g. on PRs).
- The index file can safely link off to the themes, just ```gulp docs``` and switch to the gh-pages branch if you want to see how it works.

It's not my project, so these are all my opinions, so happy if you want to leave them there :)

**Comment by iwatakeshi** [comment]
You'll have to walk me through this. :) haha. So the .gitignore file that you are referring to is the one in the master branch correct? It doesn't seem to have any `themes` folder. I did run the `gulp docs` command like so:

```bash
gulp docs
[14:45:49] Using gulpfile ~/Documents/GitHub/mr-doc/gulpfile.js
[14:45:49] Starting 'backup'...
[14:45:49] Finished 'backup' after 29 ms
[14:45:49] Starting 'beautify'...
[14:45:49] Finished 'beautify' after 75 ms
[14:45:49] Starting 'lib'...
[14:45:51] Finished 'lib' after 1.39 s
[14:45:51] Starting 'mocha'...


  Symbol
    map
      ✓ should map correctly
    compact
      ✓ should compact correctly


  2 passing (8ms)

[14:45:51] Finished 'mocha' after 59 ms
[14:45:51] Starting 'build'...
[14:45:51] Finished 'build' after 34 μs
[14:45:51] Starting 'doc'...
Mr. Doc [info]: Using theme [mr-doc-theme-default]
Mr. Doc [info]: ⠏ Rendering template.
[14:45:53] Finished 'doc' after 2.1 s
[14:45:53] Starting 'gh-pages'...
[14:45:56] [gh-pages] Cloning repo
[14:45:56] [gh-pages] Checkout remote branch `gh-pages`
[14:45:57] [gh-pages] Updating repository
[14:45:57] [gh-pages] Copying files to repository
[14:45:57] [gh-pages] Adding 71 files.
[14:45:57] [gh-pages] Committing "Update 2015-09-24T20:45:53.449Z"
[14:45:57] Finished 'gh-pages' after 4.5 s
[14:45:57] Starting 'clean-docs'...
[14:45:57] Finished 'clean-docs' after 6.95 ms
[14:45:57] Starting 'docs'...
[14:45:57] Finished 'docs' after 24 μs
Takeshis-MacBook-Pro:mr-doc iwatakeshi$ 
```
I switched to the `gh-pages` branch but I didn't see anything. Am I missing a step or two?

**Comment by cliftonc** [comment]
Mmm ... I don't think the gulp-gh-pages is working as I expect, the gh-pages branch is left untouched, but the files we want to be in the branch are put into a ```.publish``` folder.

It may be because of the ```.pipe(ghPages({push:false}));```.

The desired outcome is simple:

The gh-pages branch doesn't contain a copy of master, it simply contains the contents of the ```/docs``` folder, with the documentation created in the ```/docs/themes``` folder.

This can then be pushed up to gh-pages whenever you want to update the website.

It cleans up after itself and deletes the ```/docs/themes``` folder as that clutters the master branch if committed.

**Comment by iwatakeshi** [comment]
Just to be sure, I am to run the command on the master branch and not on the gh-pages branch correct?

**Comment by cliftonc** [comment]
Correct.

**Comment by cliftonc** [comment]
It may be that you need to delete the gh-pages branch on github and re-create (same as master?).

**Comment by iwatakeshi** [comment]
@cliftonc Hmm, well I did see the .publish folder but committing to the `master` didn't do anything on the `gh-pages` branch. I also also recreated the new `gh-pages` branch using [this tutorial](http://charliegleason.com/articles/deploying-to-github-pages-with-gulp) ...am I missing something?

**Comment by iwatakeshi** [comment]
@cliftonc After tinkering with `gulp-gh-pages` on my own [project](https://github.com/gengojs/core), I finally got it to work. I'm not sure what the issue was or if I did things properly, but in the end I had to remove the change push settings and and how the way of output for the docs. You can see the changes [here](https://github.com/mr-doc/mr-doc/blob/master/gulpfile.js).

**Comment by cliftonc** [comment]
Great, we should build a new index page and have each of the themes available to view (vs just the default), but this looks much better than the broken state I left it in.

**Comment by iwatakeshi** [comment]
I'm thinking to create an actual gh-page for the org (mr-doc) and keep this repo's gh-page as it is (probably use Cayman for it though ;) ). And maybe that will give us a better direction in creating a site that introduces Mr. Doc and also searches for themes. I'm currently looking into [harp.js](http://harpjs.com/) to build the static site.

**Comment by iwatakeshi** [comment]
@cliftonc @FGRibreau Update from this. It seems like I was right on the dot about harp.js and with it, I was able to clone most of gulp.js's site in a few hours. ;)

Heres the Main page:

<img width="1280" alt="screen shot 2015-09-27 at 12 11 30 am" src="https://cloud.githubusercontent.com/assets/1505448/10121517/dc25ed90-64ac-11e5-8840-628140c3361e.png">

Here's the Theme page using gulp's keyword temporarily.

<img width="1280" alt="screen shot 2015-09-27 at 12 12 38 am" src="https://cloud.githubusercontent.com/assets/1505448/10121520/0114223e-64ad-11e5-9eaf-54d9c6c49389.png">

The great part about harp.js was it's template agnostic server so I wrote it all in Jade and it's very easy to customize it. I haven't pushed the code yet but I hope to do so tomorrow. :)

@FGRibreau You'll probably want a domain name. Last time I checked `mr-docjs.com` is available. I haven't checked `mrdocjs.com` yet but I would think it would be available too. :)

**Comment by FGRibreau** [comment]
@iwatakeshi the new website looks awesome!

I think the domain name is currently too much, a github-page will be enough :)

**Comment by iwatakeshi** [comment]
@FGRibreau :+1:

**Comment by iwatakeshi** [comment]
@FGRibreau @cliftonc It's live! Check it out at https://mr-doc.github.io
@FGRibreau We'll need to publish the themes pretty soon. I'll give you an update once I've updated them.

**Comment by FGRibreau** [comment]
This is awesome @iwatakeshi ! I love it!

**Comment by iwatakeshi** [comment]
@FGRibreau Thanks! This is just the beginning. :) I've been researching other generators like [ESDoc](https://github.com/esdoc/esdoc) or [Groc](http://nevir.github.io/groc/) and you are right that we need a better JS doc generator. I personally think we can make Mr. Doc the go-to doc generator and hopefully get more contributors who are probably better than I am.

Once I finish my [other project](https://github.com/gengojs/gengojs). I will definitely work on the next milestone that will completely re-organize Mr. Doc. Basically, the concept of themes will stay because I think it's very powerful and useful but Mr. Doc depends too much on dox which will kill us in the future. 

I'll create a new issue and we can discuss there about how we can create our own "standard" (kinda like a subset of JSDoc and Closure compiler).
