### ISSUE TITLE
Status of 3.0.0

### ISSUE THREAD

**Issue by iwatakeshi** [mr-doc/mr-doc#95]
This is just a follow up on why 3.0.0 hasn't been released yet.

Currently I'm waiting for the following:

* Images from issue #88 
* Feedback from different users.
  * I will need **at least 5** different users to test. 
  * If you find everything to be ok then please just leave a :+1: in the comments.

To do:

* [x] Remove Coffee style docs instructions from readme and update the Github page.

**Comment by iwatakeshi** [comment]
@FGRibreau I think we'll need to add a `alpha` or some pre-release tag before publishing. Also, I looked at the package.json and I was wondering if the main file is pointed to the right file?

**Comment by FGRibreau** [comment]
@iwatakeshi :+1: for `alpha`, about the package.json I don't know :)

**Comment by iwatakeshi** [comment]
@FGRibreau Let's publish this in alpha and see what feedback we get. Images will come around in 3.0.0-rc.1. I'll leave the publishing up to you. Btw does `npm-release` support alpha tags?

**Comment by FGRibreau** [comment]
@iwatakeshi hum sadly it does not seem so https://www.npmjs.com/package/npm-release

**Comment by FGRibreau** [comment]
@iwatakeshi I'm quite busy nowadays, so I'll live the release to you, I'm sure you will do it well :) (just try to use npm-release as much as possible :))

**Comment by iwatakeshi** [comment]
@FGRibreau Sounds good to me. What should I do about the license? It's still in the year 2013.

**Comment by FGRibreau** [comment]
@iwatakeshi just update the license :)

**Comment by iwatakeshi** [comment]
@FGRibreau Nice, um are the changes committed? It still looks the same on the repo :)

**Comment by FGRibreau** [comment]
@iwatakeshi what changes? I'm sorry I clearly don't have the time to handle this right know, just do what you think you must do, it's perfectly fine for me :)

**Comment by iwatakeshi** [comment]
@FGRibreau It's ok, I was referring to the license. It hasn't change on the master.

**Comment by FGRibreau** [comment]
@iwatakeshi oh ok :)

**Comment by iwatakeshi** [comment]
@FGRibreau I know you're busy, but could you add me as the collaborator on npm. I can't publish the alpha version. Also, the license still needs to be updated on the master branch. It's still 2013 [here](https://github.com/mr-doc/mr-doc#license) and  [here](https://github.com/mr-doc/mr-doc/blob/master/LICENSE.md). ;)

**Comment by FGRibreau** [comment]
@iwatakeshi done ! :)

**Comment by iwatakeshi** [comment]
@FGRibreau Thanks, its published! :)
