### ISSUE TITLE
nvm breaks mr-doc cli

### ISSUE THREAD

**Issue by prekolna** [mr-doc/mr-doc#96]
I'm trying to use mr-doc to generate docs for my project, but a relative require in the cli is breaking with my [nvm-installed](https://github.com/creationix/nvm) node.

    » mr-doc -s ./core/ -o ./mrDoc/ -n "Triton"
    module.js:338
        throw err;
              ^
    Error: Cannot find module '../src/mr-doc'
        at Function.Module._resolveFilename (module.js:336:15)
        at Function.Module._load (module.js:286:25)
        at Module.require (module.js:365:17)
        at require (module.js:384:17)
        at Object.<anonymous> (/Users/doug.wade/.nvm/versions/io.js/v2.3.3/lib/node_modules/mr-doc/bin/mr-doc:7:11)
        at Module._compile (module.js:430:26)
        at Object.Module._extensions..js (module.js:448:10)
        at Module.load (module.js:355:32)
        at Function.Module._load (module.js:310:12)
        at Function.Module.runMain (module.js:471:10)

[Nvm](https://github.com/creationix/nvm) installs the mr-doc cli script in a separate target from the rest of the lib:

    » which mr-doc
    /Users/doug.wade/.nvm/versions/io.js/v2.3.3/bin/mr-doc

    » ls /Users/doug.wade/.nvm/versions/io.js/v2.3.3/
    CHANGELOG.md LICENSE      README.md    bin          etc          include      lib          share

The `src` folder is instead with the rest of the node module in `../lib/node_modules/mr-doc` (relative to the script in bin).

    » ls /Users/doug.wade/.nvm/versions/io.js/v2.3.3/lib/node_modules/mr-doc
    CHANGELOG.md LICENSE.md   README.md    bin          gulpfile.js  index.html   lib          node_modules package.json src

**Comment by iwatakeshi** [comment]
I think this is related to #92 . Would you mind trying Mr. Doc from the master branch?

**Comment by iwatakeshi** [comment]
@cliftonc @FGRibreau I'm not too familiar on how nvm works. Would any of you know what might be causing the issue?

**Comment by FGRibreau** [comment]
@iwatakeshi I don't think it's related with nvm but instead with io.js v2.3.3

**Comment by iwatakeshi** [comment]
@prekolna Do you have issues in Node 4.1 and have you tried installing from the master branch?

**Comment by drewlio** [comment]
I'm getting the same thing with Node 4.1.1

**Comment by drewlio** [comment]
and master works fine. 

Actually it had one hiccup resolving the dep for mr-doc-theme-default. I did this;
* **git clone** mr-doc-theme-default into mr-doc/node_modules
* **npm install** the theme
* **npm install** mr-doc

and it installed cleanly. Not sure if that's normal when installing by this method.

**Comment by iwatakeshi** [comment]
@drewlio Hmm, it shouldn't. I just updated the package.json file. Try installing Mr Doc again and let me know if the issue persists :). 

Also, finding the theme from `node_modules` happens at https://github.com/mr-doc/mr-doc/blob/master/lib/theme.js#L146-L180. You might try taking a look at the source and see if there issues with finding themes. I will gladly accept a pull request. ;)

**Comment by drewlio** [comment]
mr-doc from **master** still doesn't install cleanly.

Maybe I should ask if I'm doing this correctly. From within my app I do this:
```
cd node_modules
git clone https://github.com/mr-doc/mr-doc.git
cd mr-doc
npm install
```
and that ends with the following output:
```
npm ERR! Linux 3.13.0-57-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code ECYCLE

npm ERR! cycle Unresolvable cycle detected
npm ERR! cycle While installing: mr-doc@2.1.2
npm ERR! cycle Found a pathological dependency case that npm cannot solve.
npm ERR! cycle Please report this to the package author.
npm info preuninstall mr-doc-theme-default@1.3.1
npm info uninstall mr-doc-theme-default@1.3.1
npm info postuninstall mr-doc-theme-default@1.3.1

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/app/node_modules/mr-doc/npm-debug.log
```

**Comment by iwatakeshi** [comment]
Try installing it with `npm install https://github.com/mr-doc/mr-doc.git`. That's how I usually test and use it in my projects.

**Comment by iwatakeshi** [comment]
I'm closing this issue since I haven't heard anything. Just give me a holler if this issue persists in the upcoming alpha release.

**Comment by iwatakeshi** [comment]
@prekolna @drewlio I've released the alpha version and so far works out as expected. It should fix the issues that you were having. I can't say it will work for you since I did not test it with nvm but in theory it should work...I think Travis uses nvm correct? Anyways, if you have any issues then let me know! To install the alpha version: `sudo npm i -g mr-doc@3.0.0-alpha.2`. Happy coding!

**Comment by iwatakeshi** [comment]
I'm assuming that all is good in alpha so I'll close this for now.
